### ISSUE TITLE
incompatibility with lua5.4

### ISSUE THREAD

**Issue by multiSnow** [awesomeWM/awesome#3123]
[Lua 5.4 was released on 29 Jun 2020.](https://www.lua.org/versions.html#5.4)

[`math.randomseed` should be integer](https://www.lua.org/manual/5.4/manual.html#pdf-math.randomseed) in lua5.4, which is `g_random_int() + g_random_double()` in awesome.c, cause luaA_panic:
```
...
2020-06-30 10:48:28 W: awesome: luaA_panic:860: restarting awesome
2020-06-30 10:48:28 W: awesome: luaA_panic:855: unprotected error in call to Lua API (bad argument #1 to 'math.randomseed' (number has no integer representation))
2020-06-30 10:48:28 W: awesome: luaA_panic:859: dumping backtrace
...
```

**Comment by bittin** [comment]
Had this problem too and fighted for 2 hours and had to downgrade lua to get my wm working

**Comment by psychon** [comment]
Since #3124 is just about making AwesomeWM work with Lua 5.4: Anyone wants to do the work of adding Lua 5.4 to Travis CI?

**Comment by actionless** [comment]
> do the work of adding Lua 5.4 to Travis CI?

i can do, but i dunno which testsuites (and other env vars) to choose to be running for that setup

**Comment by psychon** [comment]
Well... you could start from what was done in `.travis.yml` before b67e0a123cb2c013f6b4665cb6030717a1463422 (back then, we built Lua 5.3 ourselves on Travis).
Most of that is "to get things working". `-ULUA_COMPAT_5_2` is to disable compatibility, so that more things break which would otherwise only break later. Same for `-DLUA_USE_APICHECK -Dlua_assert=assert`: Enable as many consistency checks as possible to find bugs.

Anyway, testing AwesomeWM with Lua 5.4 is blocked by LGI working on Lua 5.4. I don't know what the state there is (but I would expect things not to work out of the box due to API changes in lua...?

**Comment by actionless** [comment]
you right, @psychon , while luarocks is working:

```
Configuring LuaRocks version 3.0.4...

Lua interpreter found: /usr/bin/lua

Checking if /usr/bin/lua is Lua version 5.4... yes

lua.h found: /usr/include/lua5.4/lua.h

```

lgi is failing to build:

```
gcc -fPIC  -O2 -fPIC -I/usr/include/lua5.4 -pthread -I/usr/include/gobject-introspection-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wall -Wextra -O2 -g -c -o callable.o callable.c

callable.c: In function ‘closure_callback’:

callable.c:1237:13: error: too few arguments to function ‘lua_resume’

       res = lua_resume (L, NULL, npos);

             ^

In file included from lgi.h:11:0,

                 from callable.c:12:

/usr/include/lua5.4/lua.h:300:15: note: declared here

 LUA_API int  (lua_resume)     (lua_State *L, lua_State *from, int narg,

               ^
```

https://github.com/awesomeWM/awesome/pull/3127

https://travis-ci.com/github/awesomeWM/awesome/jobs/357360445

**Comment by alerque** [comment]
@actionless Luarocks‌ 3.3.1 works better where Lua 5.4 is involved.

**Comment by Aire-One** [comment]
Hello,

After facing these issues in the last few months, I found (nearly) all the places where we should update the lua interpreter reference to use lua5.3 instead of the default lua installed (which is lua5.4 on archlinux btw).

Unfortunately, I run a git rebase and reseted by local repo because I wanted it clean... So I removed all my changes, including fixes for lua version... To not make this error again, I wrote a script to apply all the necessary changes to make awesome buildable and tests runnable. You can find it as a gist at https://gist.github.com/Aire-One/d14bad0f4b22d86b829baea18b7ae6ed 🎉

BTW, I remember @psychon said he was working on a separate branch to make Awesome work with lua5.4. Is there any update on this? (https://github.com/awesomeWM/awesome/pull/3127)

**Comment by psychon** [comment]
> I remember @psychon said he was working on a separate branch to make Awesome work with lua5.4. 

Huh? Sorry, but I definitely did not do anything in that direction. Before I try to make AwesomeWM with Lua 5.4, I'd first make LGI work properly and I gave up on https://github.com/pavouk/lgi/issues/247.

> After facing these issues in the last few months, I found (nearly) all the places where we should update the lua interpreter reference to use lua5.3 instead of the default lua installed (which is lua5.4 on archlinux btw).

Sounds like we need to accept something like a `$LUA` env var to decide which Lua version to use. (Or have a CMake option to configure the Lua interpreter and then pass this on to "everything" via such an env var.) Once upon a time I had the idea to build our own Lua interpreter and use that. That should make 100% sure that during build we use the same Lua version as awesome will be using at run time. However, CMake really does not want us to compile binaries at configure time and so this idea does not work.

**Comment by Aire-One** [comment]
> > I remember @psychon said he was working on a separate branch to make Awesome work with lua5.4.
> 
> Huh? Sorry, but I definitely did not do anything in that direction. Before I try to make AwesomeWM with Lua 5.4, I'd first make LGI work properly and I gave up on [pavouk/lgi#247](https://github.com/pavouk/lgi/issues/247).

Oops! Sorry about that, I've probably over-interpreted what you said on this other discussion... 

> Sounds like we need to accept something like a `$LUA` env var to decide which Lua version to use. (Or have a CMake option to configure the Lua interpreter and then pass this on to "everything" via such an env var.)

It seems there is a start in this direction with the latest PR https://github.com/awesomeWM/awesome/pull/3279!

> Once upon a time I had the idea to build our own Lua interpreter and use that. That should make 100% sure that during build we use the same Lua version as awesome will be using at run time. However, CMake really does not want us to compile binaries at configure time and so this idea does not work.

I think I'm missing something, but:

Why couldn't we have another build step to build the awesome lua interpreter (let's say alua)? The build of awesome would depend on the alua build step, and basically, that's done.

I mean, if we build our own lua version (alua), why should it be done at configure time?

However, I'm not sure of what would be involved in "build our own lua version for awesome". We would need to maintain it, I'm afraid it would be too much additional work...

**Comment by psychon** [comment]
> Oops! Sorry about that

No problem. Sorry for giving up.

> It seems there is a start in this direction with the latest PR #3279!

I didn't see that one yet. Nice.

> why should it be done at configure time?

Because currently we already execute quite a lot of stuff at cmake configure time IIRC.

Hm, apparently we already moved some of that from cmake-configure-time to cmake-build-time. There are only four calls to `execute_process` and the only relevant one is in `tests/example/CMakeLists.txt` running the example tests. So only this one / these two cases are problematic.

There are also not many places running Lua at build time, it seems:
```
$ git grep COMMAND\ lua
awesomeConfig.cmake:        COMMAND lua ${SOURCE_DIR}/docs/06-appearance.md.lua
awesomeConfig.cmake:        COMMAND lua ${SOURCE_DIR}/docs/build_rules_index.lua
awesomeConfig.cmake:        COMMAND lua ${SOURCE_DIR}/docs/05-awesomerc.md.lua
awesomeConfig.cmake:        COMMAND lua ${SOURCE_DIR}/docs/sample_theme.lua ${BUILD_DIR}/script_files/
tests/examples/CMakeLists.txt:execute_process(COMMAND lua -e "p = package.path:gsub(';', '\\\\;'); io.stdout:write(p)"
```

Making the Lua interpreter to use configurable still sounds simpler.

> We would need to maintain it, I'm afraid it would be too much additional work...

This just takes like 5 lines of code: Load the standard modules, for each command line tell Lua to execute that file, print something on errors. It would not be very complicated, but it would definitely be the same Lua version that we later run against.

**Comment by actionless** [comment]
i saw in lgi it just got closed @psychon ?

**Comment by psychon** [comment]
Yeah, because someone claimed everything works: https://github.com/pavouk/lgi/issues/247#issuecomment-1016839629

**Comment by Elv13** [comment]
Copy paste from the other thread (because I commented in the wrong place) We have seen some `awesome -v` with 5.4 in the last year. It compile and doesn't explode.

Proof Dockerfile:

```docker
FROM ubuntu:21.04

RUN cp /etc/apt/sources.list /tmp; \
    sed -i 's/deb h/deb-src h/g' /etc/apt/sources.list; \
    cat /tmp/sources.list >> /etc/apt/sources.list

RUN apt update && apt upgrade -y && apt install git -y

RUN cat /etc/apt/sources.list

RUN DEBIAN_FRONTEND=noninteractive apt build-dep awesome lua-lgi -y
RUN apt remove lua-lgi lua-lgi-dev lua5.2 lua5.3 lua5.1 \
    liblua5.3-dev liblua5.2-dev liblua5.1-dev liblua5.1-0 \
    liblua5.1-0-dev liblua5.2-0 liblua5.3-0 -y
RUN apt install liblua5.4-dev libxcb-xfixes0-dev liblua5.4-0-dbg librsvg2-dev -y
RUN git clone https://github.com/pavouk/lgi.git
RUN sed -i 's|PKGS = |PKGS = lua |' /lgi/lgi/Makefile
RUN cd lgi && make PREFIX=/usr LUA_VERSION=5.4 && \
    make install LUA_VERSION=5.4 PREFIX=/usr

RUN git clone https://github.com/awesomewm/awesome
RUN cd awesome; sed -i 's|#error|//#error|' luaa.h
RUN cd awesome; sed -i 's|5.4.0|5.5.0|g' awesomeConfig.cmake
RUN cd awesome && make package
```

The only "patch" is to avoid calling `init_rng();` and even there to fix is minor.

```txt
root@3eb4f7cca6c8:/awesome# ./build/awesome -v
awesome v4.3-1336-g21b908be-dirty (Too long)
 • Compiled against Lua 5.4.2 (running with 0.9.2)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: /usr/share/lua/5.4/lgi/version.lua
 • Transparency enabled: yes
 • Custom search paths: no
```

![image](https://user-images.githubusercontent.com/340384/150634001-ce535589-97cd-4a15-b6fa-5f38e0d22d7d.png)

```lua
diff --git a/awesome.c b/awesome.c
index 24ee52d8..ef6c339e 100644
--- a/awesome.c
+++ b/awesome.c
@@ -37,6 +37,7 @@
 #include "systray.h"
 #include "xwindow.h"
 #include "options.h"
+#include "math.h"
 
 #include <getopt.h>
 
@@ -84,10 +85,16 @@ init_rng(void)
     lua_getfield(L, -1, "randomseed");
 
     /* Push a seed */
-    lua_pushnumber(L, g_random_int() + g_random_double());
+    lua_pushnumber(L, floor(g_random_int() + g_random_double()));
 
     /* Call math.randomseed */
-    lua_call(L, 1, 0);
+    if(lua_pcall(L, 1, 0, 0))
+    {
+        warn("Random number generator initialization failed: %s", lua_tostring(L, -1));
+        /* Remove error function and error string */
+        lua_pop(L, 2);
+        return;
+    }
 
     /* Remove "math" global */
     lua_pop(L, 1);
diff --git a/awesomeConfig.cmake b/awesomeConfig.cmake
index 5f292aaa..592c2b25 100644
--- a/awesomeConfig.cmake
+++ b/awesomeConfig.cmake
@@ -73,9 +73,9 @@ if (NOT LUA_FOUND)
 endif()
 
 set(LUA_FULL_VERSION "${LUA_VERSION_MAJOR}.${LUA_VERSION_MINOR}.${LUA_VERSION_PATCH}")
-# 5.1 <= LUA_VERSION < 5.4
-if(NOT ((LUA_FULL_VERSION VERSION_EQUAL 5.1.0 OR LUA_FULL_VERSION VERSION_GREATER 5.1.0) AND LUA_FULL_VERSION VERSION_LESS 5.4.0))
-    message(FATAL_ERROR "Awesome only supports Lua versions 5.1-5.3, please refer to"
+# 5.1 <= LUA_VERSION < 5.5
+if(NOT ((LUA_FULL_VERSION VERSION_EQUAL 5.1.0 OR LUA_FULL_VERSION VERSION_GREATER 5.1.0) AND LUA_FULL_VERSION VERSION_LESS 5.5.0))
+    message(FATAL_ERROR "Awesome only supports Lua versions 5.1-5.4, please refer to"
                         "https://awesomewm.org/apidoc/documentation/10-building-and-testing.md.html#Building")
 endif()
 
diff --git a/luaa.h b/luaa.h
index fae07270..04e28342 100644
--- a/luaa.h
+++ b/luaa.h
@@ -31,8 +31,8 @@
 #include "common/lualib.h"
 #include "common/luaclass.h"
 
-#if !(501 <= LUA_VERSION_NUM && LUA_VERSION_NUM < 504)
-#error "Awesome only supports Lua versions 5.1-5.3 and LuaJIT2, please refer to https://awesomewm.org/apidoc/documentation/10-building-and-testing.md.html#Building"
+#if !(501 <= LUA_VERSION_NUM && LUA_VERSION_NUM < 505)
+#error "Awesome only supports Lua versions 5.1-5.4 and LuaJIT2, please refer to https://awesomewm.org/apidoc/documentation/10-building-and-testing.md.html#Building"
 #endif
 
 #define luaA_deprecate(L, repl) \
```

**Comment by Elv13** [comment]
Actually, with the patch above, all tests pass. I don't really know what's next for this ticket. Just PR-ing the patch above and adding the Lua 5.4 CI is "enough", but then we will get more bug report because LGI isn't properly installed. So maybe we need to be more string about a working LGI matching the same Lua `_VERSION` is the liblua used by AwesomeWM at compile time?

**Comment by alerque** [comment]
Does anybody know of a patch that is backported to apply on Awesome 4.3? The one above, the old comment version of the one above, and the (different) ones that ended up in master all seem different, but they all work from Git HEAD. That's reasonable for development, but unless a new version bump is immanent  it would be nice to get some distro stuff ublocked if backporting this is reasonable. I have `lua-lgi` ready for Arch Linux (in [community-testing] now).

**Comment by actionless** [comment]
no, 4.3 branch is not supported

you can backport the one which is in master, it seems to work so far with lua-lgi-git from aur
