### ISSUE TITLE
Fails to build with libxkbcommon >= 1.0

### ISSUE THREAD

**Issue by jknox13** [awesomeWM/awesome#3168]
**Summary**
Arch AUR fails to build due to `xkb_utf32_to_keysym()` declaration inconsistency

**How to reproduce the issue:**

**Follow Arch AUR install instructions from README.md**
```
sudo pacman -S --needed base-devel git
git clone https://aur.archlinux.org/awesome-git.git
cd awesome-git
makepkg -fsri
```

**Actual result:**

```shell
[ 78%] Building C object CMakeFiles/awesome.dir/luaa.c.o
In file included from /home/joseph/awesome-git/src/build/luaa.c:80:
/home/joseph/awesome-git/src/build/xkb_utf32_to_keysym.c:842:21: error: static declaration of ‘xkb_utf32_to_keysym’ follows non-static declaration
  842 | static xkb_keysym_t xkb_utf32_to_keysym(uint32_t ucs)
      |                     ^~~~~~~~~~~~~~~~~~~
In file included from /home/joseph/awesome-git/src/build/objects/key.h:26,
                 from /home/joseph/awesome-git/src/build/globalconf.h:41,
                 from /home/joseph/awesome-git/src/build/luaa.c:45:
/usr/include/xkbcommon/xkbcommon.h:517:1: note: previous declaration of ‘xkb_utf32_to_keysym’ was here
  517 | xkb_utf32_to_keysym(uint32_t ucs);
      | ^~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/awesome.dir/build.make:186: CMakeFiles/awesome.dir/luaa.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1967: CMakeFiles/awesome.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Expected result:**

(Build completes successfully)

**Comment by jknox13** [comment]
**Compiler Versions**
```shell
>> cmake --version
cmake version 3.18.2
```

```shell
>> gcc --version
gcc (GCC) 10.2.0
```

**Comment by F0xedb** [comment]
I have the same issue, for those who are not familiar with arch/AUR, here is the PKGBUILD (build script) that fails https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=awesome-git

**Comment by Glitch18** [comment]
Same here. I tried both, using `yay -S awesome-git` and by -

```
git clone https://aur.archlinux.org/awesome-git.git
cd awesome-git
makepkg -fsri
```
both give the same error while trying to build.

**Comment by psychon** [comment]
This is caused by a change in libxkbcommon. Per https://lists.freedesktop.org/archives/wayland-devel/2020-September/041596.html: "- Add `xkb_utf32_to_keysym()` to translate a Unicode codepoint to a keysym. [...]"

The possible fixes that I see are to write some CMake configure machinery magic to check whether libxkbcommon provides the function, or alternative to just make AwesomeWM depend on libxkbcommon > 1.0 (which might be better long-term, but worse short-term).

`git log xkb_utf32_to_keysym.c` says only one commit touched this file, so CC @ArenaL5 who authored #3011:

> commit 8bac3a4acbadb35c4b2d624df7a7b84c123d689c
> Author: ArenaL5 <arenal5@gmx.com>
> Date:   Wed Feb 26 21:03:37 2020 +0100
>
>    Add C API to query keys
>    
>    `awesome.get_key_name()` accepts a key in any format that `awful.key()` understands (querying current locale configuration if fed a keycode), and returns its keysym name and printable representation, if any.
>    
>    This method is based in development code from xkbcommon/libxkbcommon that has not yet been released in a stable API; for this reason, code from https://github.com/xkbcommon/libxkbcommon/commit/0345aba082c83e9950f9dd8b7ea3bf91fe566a02 has been copied into a new C file.
>    
>    Signed-off-by: ArenaL5 <arenal5@gmx.com>
