### PR TITLE
Quick fix to support libxkbcommon >= 1.0.

### LINKED ISSUE #3168: Fails to build with libxkbcommon >= 1.0
**Summary**
Arch AUR fails to build due to `xkb_utf32_to_keysym()` declaration inconsistency

**How to reproduce the issue:**

**Follow Arch AUR install instructions from README.md**
```
sudo pacman -S --needed base-devel git
git clone https://aur.archlinux.org/awesome-git.git
cd awesome-git
makepkg -fsri
```

**Actual result:**

```shell
[ 78%] Building C object CMakeFiles/awesome.dir/luaa.c.o
In file included from /home/joseph/awesome-git/src/build/luaa.c:80:
/home/joseph/awesome-git/src/build/xkb_utf32_to_keysym.c:842:21: error: static declaration of ‘xkb_utf32_to_keysym’ follows non-static declaration
  842 | static xkb_keysym_t xkb_utf32_to_keysym(uint32_t ucs)
      |                     ^~~~~~~~~~~~~~~~~~~
In file included from /home/joseph/awesome-git/src/build/objects/key.h:26,
                 from /home/joseph/awesome-git/src/build/globalconf.h:41,
                 from /home/joseph/awesome-git/src/build/luaa.c:45:
/usr/include/xkbcommon/xkbcommon.h:517:1: note: previous declaration of ‘xkb_utf32_to_keysym’ was here
  517 | xkb_utf32_to_keysym(uint32_t ucs);
      | ^~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/awesome.dir/build.make:186: CMakeFiles/awesome.dir/luaa.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1967: CMakeFiles/awesome.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Expected result:**

(Build completes successfully)

### PR DESCRIPTION
**Pull request by Elv13**
This is a quick fix to move our copy of the code to avoid the name collision.  The next step will be to use the "real" function when a `libxkbcommon` version is found rather than the compat version. This will be another PR

Fix #3168

### CODE REVIEW

**Review by Glitch18 — APPROVED** [review]

**Review by actionless — APPROVED** [review]

**Review by psychon — APPROVED** [review]
Nice hack to solve this easily. :-)
