### ISSUE TITLE
Eclipse detached windows cannot be moved to different screen

### ISSUE THREAD

**Issue by crater2150** [awesomeWM/awesome#1406]
Eclipse can detach panels as separate windows (by dragging them out of the main window). In Awesome 3.5 I could launch Eclipse on the main screen and move some panels to the second screen.

Since the upgrade to awesome 4.0, the panels can no longer be moved to a screen different from the main window. Trying to move a panel to the other screen by keyboard does nothing, making it floating and dragging causes it to jump back as soon as the last pixel leaves the screen with the main window. If the main window was on another tag, the subwindow is even placed on that tag, instead of the one it was before.
What **does** work is moving the main window to a different screen, this does not move the detached windows. This workaround is limited, as I can still only place the subwindows on one screen.

[xprop output for main window](https://github.com/awesomeWM/awesome/files/708029/xprop_main_window.txt)
[xprop output for detached panel window](https://github.com/awesomeWM/awesome/files/708030/xprop_detached_window.txt)

Output of `awesome --version`:

awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.2.4 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

**How to reproduce the issue:**

1. Start eclipse
2. Detach a panel by dragging
3. try to move panel to a different screen

**Actual result:**

detached panel jumps back to screen of main eclipse window

**Expected result:**

detached panel should be shown on different screen

**Comment by Elv13** [comment]
Can you create a new user account on your system (to avoid messing up your "real" one) and do a `git bisect` of this? You will have to use the default config for each steps as it changed many, many time in the 2300 commits delta. Use a `LUA_PATH` environment variable (the newer revisions have `--search`, but 3.5 doesn't) it wont take much time.

You can't use Xephyr for this (even with xinerama enabled, it wont reproduce the bug correctly), so use `X :1` to start a second X server (ctrl+alt+f8 to access it)

**Comment by crater2150** [comment]
A lot of revisions fail to link for me with 

    /usr/sbin/ld: CMakeFiles/awesome.dir/awesome.c.o: undefined reference to symbol 'XSetEventQueueOwner'
    /lib64/libX11-xcb.so.1: error adding symbols: DSO missing from command line
    collect2: error: ld returned 1 exit status

so I need to `git bisect skip` them. The current master and the v3.5 tag do compile, as do some revisions in between. Is this to be expected?

**Comment by Elv13** [comment]
Not really, I am not aware of any revision that fails to compile. Some do fail the tests, but maybe ~10 commits (of ~2300). Maybe you need to clear the build directory?

**Comment by crater2150** [comment]
After fixing my build (probably a combination of missing libXres and using `make clean` instead of `distclean`) and some other problems, the bisect finally ran through.
The first commit with the issue is 21787444e4f1

**Comment by psychon** [comment]
(The build failure is due to CMake once again caching too much things)

**Comment by blueyed** [comment]
Looks like @psychon found something there: https://github.com/awesomeWM/awesome/commit/21787444e4f12441735cd4080337469e33ab417a#commitcomment-20510658.

@crater2150 
Can you check if re-adding the check for `type ~= 'dock'` there fixes it?
If so, please consider creating a PR from there with the previous check from below.

**Comment by crater2150** [comment]
Adding a check there, that excludes the eclipse window helps, but sadly the type for the undocked panels is not `dock` but `dialog` (although xprop returns `_NET_WM_WINDOW_TYPE_NORMAL`).
If I understand correctly, excluding dialogs would defeat the whole purpose of `transient_for` :-/

**Comment by Elv13** [comment]
Ok, so one of the `request::tag` and `property::screen` probably (?) end up fighting each other until they settle on "do nothing". The solution is probably using the hints argument in `ewmh.tag` to "break the loop". You could add `and not (hints and hints.reason == "screen")` to the  `transient_for` `if`. I will need to carefully see if this has any other unwanted side effects. As I wrote in #1091, getting this to work all the time isn't easy. These changes were made because of yet more bugs of this kind. I think the new screen decision code is much saner than the old one, but it's far from perfect.

**Comment by psychon** [comment]
Should this be closed? Isn't #1452 supposed to fix it?
